apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-sc
  nfs:
    server: 192.168.133.17
    path: /nfs

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-sc
provisioner: kubernetes.io/no-provisioner
#volumeBindingMode: WaitForFirstConsumer
