apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin


  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: munnaeeebd/mn-phpmyadmin

          ports:
           - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql-service
#            - name: PMA_PORT
#              value: "3306"
#            - name: MYSQL_ROOT_PASSWORD
#              value: password
          volumeMounts:
              - name: nfs-volume-pvc
                mountPath: /nfs-client2
      volumes:
      - name: nfs-volume-pvc
        persistentVolumeClaim:
         claimName: nfs
